const fooddata = [
    {
      _id: 1,
      name: 'Noodle',
      origin: 'Vietnam',
      price: 10,
      description: 'Delicious Vietnamese noodle dish',
      date: '03/23/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 2,
      name: 'Burger',
      origin: 'United States',
      price: 8,
      description: 'Classic American burger',
      date: '03/24/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 3,
      name: 'Pizza',
      origin: 'Italy',
      price: 12,
      description: 'Traditional Italian pizza',
      date: '03/25/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 4,
      name: 'Sushi',
      origin: 'Japan',
      price: 15,
      description: 'Fresh Japanese sushi rolls',
      date: '03/26/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 6,
      name: 'Pasta',
      origin: 'Italy',
      price: 11,
      description: 'Classic Italian pasta dish',
      date: '03/28/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 7,
      name: 'Sushi Burrito',
      origin: 'United States',
      price: 13,
      description: 'A fusion of sushi and burrito',
      date: '03/29/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 8,
      name: 'Curry',
      origin: 'India',
      price: 12,
      description: 'Spicy and aromatic Indian curry',
      date: '03/30/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 9,
      name: 'Pho',
      origin: 'Vietnam',
      price: 10,
      description: 'Traditional Vietnamese noodle soup',
      date: '03/31/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
    {
      _id: 10,
      name: 'Sushi Roll',
      origin: 'Japan',
      price: 16,
      description: 'Variety of Japanese sushi rolls',
      date: '04/01/2023',
      image: { uri: 'https://picsum.photos/200' },
    },
   
  ];
  
  export {fooddata};