const fooddata = [
    {
      _id: 1,
      name: 'Noodle',
      origin: 'Vietnam',
      price: 10,
      description: 'Delicious Vietnamese noodle dish',
      date: '03/23/2023',
      image: { uri: 'https://media-cdn.tripadvisor.com/media/photo-s/0e/79/18/22/handpulled-noddle.jpg' },
    },
    {
      _id: 2,
      name: 'Burger',
      origin: 'United States',
      price: 8,
      description: 'Classic American burger',
      date: '03/24/2023',
      image: { uri: 'https://www.mashed.com/img/gallery/fast-food-hamburgers-ranked-worst-to-best/intro-1540401194.jpg' },
    },
    {
      _id: 3,
      name: 'Pizza',
      origin: 'Italy',
      price: 12,
      description: 'Traditional Italian pizza',
      date: '03/25/2023',
      image: { uri: 'https://previews.123rf.com/images/yauhen0409/yauhen04091805/yauhen0409180500103/101107190-pizza-shooting-various-kinds-of-pizzas-for-the-menu-of-fast-food-restaurant-and-pizzeria-fast-food.jpg' },
    },
    {
      _id: 4,
      name: 'Sushi',
      origin: 'Japan',
      price: 15,
      description: 'Fresh Japanese sushi rolls',
      date: '03/26/2023',
      image: { uri: 'https://www.happyfoodstube.com/wp-content/uploads/2016/03/homemade-sushi-image.jpg' },
    },
    {
      _id: 6,
      name: 'Pasta',
      origin: 'Italy',
      price: 11,
      description: 'Classic Italian pasta dish',
      date: '03/28/2023',
      image: { uri: 'https://myfoodstory.com/wp-content/uploads/2023/01/air-fryer-pasta-square-2.jpg' },
    },
    {
      _id: 7,
      name: 'Sushi Burrito',
      origin: 'United States',
      price: 13,
      description: 'A fusion of sushi and burrito',
      date: '03/29/2023',
      image: { uri: 'https://www.sidechef.com/recipe/0fbd70b3-d17d-4928-952f-80f4ebf19c6f.jpg' },
    },
    {
      _id: 8,
      name: 'Curry',
      origin: 'India',
      price: 12,
      description: 'Spicy and aromatic Indian curry',
      date: '03/30/2023',
      image: { uri: 'https://www.kitchensanctuary.com/wp-content/uploads/2022/09/Air-Fryer-Chicken-Curry-square-FS-36.jpg' },
    },
    {
      _id: 9,
      name: 'Pho',
      origin: 'Vietnam',
      price: 10,
      description: 'Traditional Vietnamese noodle soup',
      date: '03/31/2023',
      image: { uri: 'https://iamafoodblog.b-cdn.net/wp-content/uploads/2017/11/authentic-instant-pot-pho-recipe-1959w-1024x683.jpg' },
    },
    {
      _id: 10,
      name: 'Sushi Roll',
      origin: 'Japan',
      price: 16,
      description: 'Variety of Japanese sushi rolls',
      date: '04/01/2023',
      image: { uri: 'https://sudachirecipes.com/wp-content/uploads/2022/08/ehomaki-thumbnail.jpg' },
    },
   
  ];
  
  export {fooddata};